<a href="https://colab.research.google.com/github/BrunoAlexandreAmaral/modelo_clasificacao/blob/main/modelo___LogisticRegression___Classifica%C3%A7%C3%A3o.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from google.colab import files
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,balanced_accuracy_score,precision_score,recall_score,f1_score,roc_auc_score

In [ ]:
uploaded = files.upload()

Saving Bank_Personal_Loan_Modelling.xlsx to Bank_Personal_Loan_Modelling.xlsx

In [ ]:
df = pd.read_excel("Bank_Personal_Loan_Modelling.xlsx")

In [ ]:
df.head()

,ID,Age,Experience,Income,Family,CCAvg,Education,Mortgage,Personal_Loan,Securities_Account,CD_Account,Online,CreditCard
0,1,25,1,49,4,1.6,1,0,0,1,0,0,0
1,2,45,19,34,3,1.5,1,0,0,1,0,0,0
2,3,39,15,11,1,1.0,1,0,0,0,0,0,0
3,4,35,9,100,1,2.7,2,0,0,0,0,0,0
4,5,35,8,45,4,1.0,2,0,0,0,0,0,1

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ID                  5000 non-null   int64
 1   Age                 5000 non-null   int64
 2   Experience          5000 non-null   int64
 3   Income              5000 non-null   int64
 4   Family              5000 non-null   int64
 5   CCAvg               5000 non-null   float64
 6   Education           5000 non-null   int64
 7   Mortgage            5000 non-null   int64
 8   Personal_Loan       5000 non-null   int64
 9   Securities_Account  5000 non-null   int64
 10  CD_Account          5000 non-null   int64
 11  Online              5000 non-null   int64
 12  CreditCard          5000 non-null   int64
dtypes: float64(1), int64(12)
memory usage: 507.9 KB

In [ ]:
df.isnull().sum()

ID                    0
Age                   0
Experience            0
Income                0
Family                0
CCAvg                 0
Education             0
Mortgage              0
Personal_Loan         0
Securities_Account    0
CD_Account            0
Online                0
CreditCard            0
dtype: int64

In [ ]:
df.duplicated().sum()

0

In [ ]:
df = df.drop("ID",axis=1)

In [ ]:
df.columns

Index(['Age', 'Experience', 'Income', 'Family', 'CCAvg', 'Education',
       'Mortgage', 'Personal_Loan', 'Securities_Account', 'CD_Account',
       'Online', 'CreditCard'],
      dtype='object')

In [ ]:
x= df.drop("Personal_Loan", axis=1)
y = df["Personal_Loan"]

In [ ]:
x

,Age,Experience,Income,Family,CCAvg,Education,Mortgage,Securities_Account,CD_Account,Online,CreditCard
0,25,1,49,4,1.6,1,0,1,0,0,0
1,45,19,34,3,1.5,1,0,1,0,0,0
2,39,15,11,1,1.0,1,0,0,0,0,0
3,35,9,100,1,2.7,2,0,0,0,0,0
4,35,8,45,4,1.0,2,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...
4995,29,3,40,1,1.9,3,0,0,0,1,0
4996,30,4,15,4,0.4,1,85,0,0,1,0
4997,63,39,24,2,0.3,3,0,0,0,0,0
4998,65,40,49,3,0.5,2,0,0,0,1,0
4999,28,4,83,3,0.8,1,0,0,0,1,1

In [ ]:
y

0       0
1       0
2       0
3       0
4       0
       ..
4995    0
4996    0
4997    0
4998    0
4999    0
Name: Personal_Loan, Length: 5000, dtype: int64

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2, random_state = 42)

In [ ]:
lr = LogisticRegression()

In [ ]:
lr_treinado = lr.fit(x_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [ ]:
predito = lr_treinado.predict(x_test)

In [ ]:
x_test.assign(y_test = y_test).assign(predito = predito).head(30)

,Age,Experience,Income,Family,CCAvg,Education,Mortgage,Securities_Account,CD_Account,Online,CreditCard,y_test,predito
1501,30,4,35,2,0.3,2,0,1,0,0,1,0,0
2586,47,23,149,4,6.1,1,0,0,0,0,1,1,0
2653,30,5,121,2,3.1,1,408,0,0,1,0,0,0
1055,31,6,62,1,1.0,1,0,1,0,1,0,0,0
705,62,36,30,3,0.7,2,0,0,0,1,0,0,0
106,43,17,69,4,2.9,1,0,0,0,1,1,0,0
589,31,7,128,1,6.0,1,0,0,0,0,0,0,0
2468,49,23,133,1,7.3,1,0,0,0,1,1,0,0
2413,60,34,31,2,1.0,3,0,0,0,0,0,0,0
1600,60,36,129,2,6.0,1,0,0,0,1,0,0,0
2464,60,36,32,3,0.4,2,165,0,0,1,0,0,0
228,47,22,53,4,1.9,3,98,1,1,0,1,0,0
915,53,28,184,1,8.1,1,303,0,0,1,0,0,0
794,54,29,44,2,2.3,3,0,0,0,1,0,0,0
3021,54,28,159,2,0.5,1,461,0,0,1,0,0,0
3543,37,11,194,2,0.0,1,0,0,0,0,0,0,0
1073,33,8,122,1,0.0,1,0,0,0,1,1,0,0
3351,52,26,191,1,1.7,1,0,0,0,1,0,0,0
1744,28,3,29,4,0.8,1,135,0,0,1,0,0,0
1084,60,35,191,4,5.6,3,0,0,0,0,0,1,1
926,33,9,22,4,0.4,2,103,0,0,1,0,0,0
3049,60,35,125,2,3.9,1,0,0,0,0,0,0,0
1117,42,18,145,1,1.7,1,132,0,0,1,1,0,0
642,50,24,103,1,0.3,1,0,0,0,1,0,0,0
4767,35,9,45,3,0.9,1,101,1,0,0,0,0,0
501,50,26,39,3,1.9,2,0,0,0,1,0,0,0
4066,61,37,61,3,2.0,3,0,0,0,1,0,0,0
333,63,38,140,1,2.5,1,0,0,0,0,0,0,0
4684,59,34,103,1,2.6,1,0,0,0,1,0,0,0
486,55,30,84,2,3.7,1,304,1,0,1,0,0,0

In [56]:
print(f"Acurario do treino: {accuracy_score(y_train,lr_treinado.predict(x_train))}")
print(f"Acurario do teste: {accuracy_score(y_test,lr_treinado.predict(x_test))}")
print("="*40)
print(f"Acuracia Balanceada treino: {balanced_accuracy_score(y_train,lr_treinado.predict(x_train))}")
print(f"Acuracia Balanceada test: {balanced_accuracy_score(y_test,lr_treinado.predict(x_test))}")
print("="*40)
print(f"Recall treino: {recall_score(y_train,lr_treinado.predict(x_train))}")
print(f"Recall teste: {recall_score(y_test,lr_treinado.predict(x_test))}")
print("="*40)
print(f"Precisão treino: {precision_score(y_train,lr_treinado.predict(x_train))}")
print(f"Precisão teste: {precision_score(y_test,lr_treinado.predict(x_test))}")
print("="*40)
print(f"Roc AUC Treino : {roc_auc_score(y_train,lr_treinado.predict_proba(x_train)[:,1])}")
print(f"Roc AUC Test : {roc_auc_score(y_test,lr_treinado.predict_proba(x_test)[:,1])}")

Acurario do treino: 0.949
Acurario do teste: 0.953
========================================
Acuracia Balanceada treino: 0.7829885057471264
Acuracia Balanceada test: 0.8224261771747805
========================================
Recall treino: 0.5786666666666667
Recall teste: 0.6571428571428571
========================================
Precisão treino: 0.8250950570342205
Precisão teste: 0.8625
========================================
Roc AUC Treino : 0.9507361839080459
Roc AUC Test : 0.9655972333067305